name: Ejecutar mi programa cada dia

on:
  schedule:
    - cron: '59 23 * * *' # Se ejecuta a las 23:59 todos los días
  workflow_dispatch: # Esto te permite darle a un botón para probarlo ahora

jobs:
  tarea_diaria:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Permiso para que el robot pueda subir el archivo generado
    
    steps:
      - name: 1. Descargar mi codigo de GitHub
        uses: actions/checkout@v4

      - name: 2. Preparar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 3. Ejecutar mi script de tiempo
        run: python tiempo.py # Ejecuta tu archivo tiempo.py

      - name: 4. Guardar y subir el archivo generado
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Nuevo reporte de temperaturas"
          file_pattern: '*.json *.txt' # Guarda cualquier archivo .json o .txt que se cree
