name: Ejecutar mi programa cada dia

on:
  schedule:
    - cron: '59 23 * * *'
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  tarea_diaria:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: 1. Descargar mi codigo
        uses: actions/checkout@v4

      - name: 2. Preparar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 3. Ejecutar mi script
        run: python tiempo.py

      - name: 4. Guardar y subir el archivo
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Nuevo reporte de temperaturas"
          file_pattern: '.' # El punto significa "guarda cualquier cambio que encuentres"
